@CleanMind.API_HostAddress = http://localhost:5075/api/Clinic


### UpdateClinicName
PUT {{CleanMind.API_HostAddress}}/UpdateClinicName/019f4cd8-adc3-766a-b7eb-b982c944a777
Content-Type: application/json

{
  "name":"Psychotherapy Clinic 75"
}

### GetAllClinics
GET {{CleanMind.API_HostAddress}}/GetAllClinics
ACCEPT: application/json

###Get Clinic By Id
GET {{CleanMind.API_HostAddress}}/GetClinicById/019f4cd8-adc3-766a-b7eb-b982c944a777
ACCEPT: application/json


### Create Clinic
POST {{CleanMind.API_HostAddress}}/CreateClinic
Content-Type: application/json

{
  "name":"Psychotherapy Clinic 02"
}
###
